version: '3.7'

services:
  app:
    build: .
    command: gunicorn bot_api.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
  nginx:
    build: ./nginx
    ports:
      - 3333:3333
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
volumes:
  media_volume:
  static_volume: