# Generated by Django 3.1 on 2020-08-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название мануала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показ мануала')),
            ],
        ),
        migrations.CreateModel(
            name='ManualItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='manuals/', verbose_name='Картинка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manualcategory', verbose_name='Мануал')),
            ],
        ),
    ]
